project:
  type: website

website:
  title: "Inupiaq postbase tool"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: story 1.qmd
        text: Stories
  search: True

format:
  html:
    theme: darkly
    css: styles2.css
    toc: true

editor: visual

